# docker-compose prod.yml
version: '3'

services:
  auth_db:
    image: postgres:13-alpine
    container_name: auth_db
    env_file: 
      - ./.env
    volumes:
      - auth_db_data:/var/lib/postgresql/data/
    restart: always
    networks:
      - auth_net

  redis:
    image: redis:alpine
    container_name: redis
    env_file: 
      - ./.env
    volumes:
      - redis_data:/data
    restart: always
    networks:
      - auth_net

  flask_auth:
    build: ./flask_auth
    container_name: flask_auth
    environment:
      - PYTHONPATH=/flask_auth
    env_file:
      - .env
    working_dir: /flask_auth
    depends_on:
      - redis
      - auth_db
    ports:
      - "5000:5000"
    restart: always
    networks:
      - auth_net




volumes:
  auth_db_data:
  redis_data:

networks:
  auth_net:
    driver: bridge
