# Generated by Django 4.1.7 on 2023-03-03 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ResponseGetCreateUser',
            fields=[
                ('notifid', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='_id')),
                ('user_id', models.CharField(max_length=255, verbose_name='user_id')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('status', models.BooleanField(verbose_name='status')),
            ],
        ),
    ]
