# Generated by Django 4.1.7 on 2023-03-03 12:27

from django.db import migrations, models
import djongo.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('admin_notif', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreateUser',
            fields=[
                ('_id', djongo.models.fields.ObjectIdField(auto_created=True, primary_key=True, serialize=False, verbose_name='notifid')),
                ('user_id', models.CharField(max_length=255, verbose_name='user_id')),
                ('username', models.CharField(max_length=255, verbose_name='username')),
                ('email', models.CharField(max_length=255, verbose_name='email')),
                ('status', models.BooleanField(verbose_name='status')),
            ],
        ),
        migrations.DeleteModel(
            name='ResponseGetCreateUser',
        ),
    ]
