# Generated by Django 4.1.7 on 2023-03-16 19:40

from django.db import migrations, models
import django_better_admin_arrayfield.models.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AdminNotifEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('notification_type', models.CharField(choices=[('user_create', 'User Create'), ('change_password', 'Change Password'), ('new_films', 'New Films'), ('received_likes', 'Received Likes')], default='new_films', max_length=255)),
                ('notification_data', models.DateTimeField(auto_now=True)),
                ('notification_text', models.CharField(max_length=511, null=True)),
                ('status', models.BooleanField(default=False, verbose_name='status')),
                ('user_ids', django_better_admin_arrayfield.models.fields.ArrayField(base_field=models.UUIDField(), size=None)),
            ],
            options={
                'db_table': 'adminnotifevent',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, unique=True, verbose_name='id')),
                ('notification_type', models.CharField(choices=[('user_create', 'User Create'), ('change_password', 'Change Password'), ('new_films', 'New Films'), ('received_likes', 'Received Likes')], max_length=255)),
                ('notification_text', models.CharField(max_length=255, null=True)),
                ('notification_data', models.DateTimeField(auto_now=True)),
                ('status', models.BooleanField(default=False)),
                ('ready', models.BooleanField(default=False)),
                ('user_id', models.UUIDField()),
                ('user_name', models.CharField(max_length=255, null=True)),
                ('user_email', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'notifications',
                'managed': False,
            },
        ),
    ]
